/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.bookmaintenance;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author livlucas
 */
public class BookMaintenanceUI extends javax.swing.JFrame {

    /**
     * Creates new form BookMaintenanceUI
     */
    
    BookDatabase db = null;
    ArrayList<BookRecord> bookRecords;
    int currentBookRecord = 0;
    ModeEnum formMode;
    
    public BookMaintenanceUI() {
        initComponents();
        loadData();
        setDefaultMode();
    }

    private void loadData() {
        db = new BookDatabase();
        db.initConnection();
        bookRecords = db.FetchAll();
    }
    
    private void displayCurrentBookRecord() {
        BookRecord bookRecord = bookRecords.get(currentBookRecord);
        
        setTitleLabel("Showing Record #" + bookRecord.getId());
        this.txt_code.setText(bookRecord.getCode());
        this.txt_title.setText(bookRecord.getTitle());
        this.txt_price.setText(bookRecord.getPrice().toString());
    }
    
    private void setDefaultMode() {
        if (bookRecords.isEmpty()) {
            setAddMode();
            return;
        }

        formMode = ModeEnum.DEFAULT;
        this.setEnabledAllButtons(true);
        updateButton.setEnabled(false);
        displayCurrentBookRecord();
    }
    //adding new records
    private void setAddMode() {
        formMode = ModeEnum.ADD;

        setTitleLabel("Adding new Record");
        txt_code.setText("");
        txt_price.setText("");
        txt_title.setText("");
        txt_code.setCaretPosition(0);
        
        setEnabledAllButtons(false);
        updateButton.setEnabled(true);
        updateButton.setText("Save");
    }
    //user in update mode
    private void setUpdateMode() {
        formMode = ModeEnum.UPDATE;
        
        setTitleLabel("Updating Record #" + bookRecords.get(currentBookRecord).getId());
        setEnabledAllButtons(false);
        updateButton.setEnabled(true);
    }
    
    //setting the title on top of program
    private void setTitleLabel(String message) {
        String count;
        if (bookRecords.isEmpty()) {
            count = "(empty db)";
        } else {
            count = "(total: " + bookRecords.size() + ")";
        }
        this.currentRecordLabel.setText(message + " " + count);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_code = new javax.swing.JTextField();
        txt_title = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        firstButton = new javax.swing.JButton();
        prevButton = new javax.swing.JButton();
        nextButton = new javax.swing.JButton();
        lastButton = new javax.swing.JButton();
        currentRecordLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_code.setText("Change me");
        txt_code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codeActionPerformed(evt);
            }
        });
        txt_code.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_codePropertyChange(evt);
            }
        });
        txt_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codeKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codeKeyReleased(evt);
            }
        });

        txt_title.setText("Change me");
        txt_title.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_titleKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_titleKeyReleased(evt);
            }
        });

        txt_price.setText("Change me");
        txt_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_priceKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_priceKeyReleased(evt);
            }
        });

        jLabel1.setText("Code:");

        jLabel2.setText("Title:");

        jLabel3.setText("Price:");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        firstButton.setText("« First");
        firstButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstButtonActionPerformed(evt);
            }
        });

        prevButton.setText("< Prev");
        prevButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevButtonActionPerformed(evt);
            }
        });

        nextButton.setText("Next >");
        nextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButtonActionPerformed(evt);
            }
        });

        lastButton.setText("Last »");
        lastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastButtonActionPerformed(evt);
            }
        });

        currentRecordLabel.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prevButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(currentRecordLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_title))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_code))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_price)))
                                .addGap(147, 147, 147)))
                        .addGap(119, 119, 119))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addButton, deleteButton, exitButton, firstButton, lastButton, nextButton, prevButton, updateButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentRecordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(updateButton)
                    .addComponent(deleteButton)
                    .addComponent(exitButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstButton)
                    .addComponent(prevButton)
                    .addComponent(nextButton)
                    .addComponent(lastButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codeActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        setAddMode();
    }//GEN-LAST:event_addButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        Double price;
        BookRecord bookRecord;

        if (formMode == ModeEnum.ADD) {
            bookRecord = new BookRecord();
        } else {
            //update
            bookRecord = bookRecords.get(currentBookRecord);
        }
        
        try {
            bookRecord.setPrice(txt_price.getText());
        } catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Price format must be $$.$, where $ is a number.");
            txt_price.selectAll();
            txt_price.grabFocus();
            txt_price.requestFocus();
            return;
        }
        
        bookRecord.setCode(txt_code.getText());
        bookRecord.setTitle(txt_title.getText());
        
        db.updateRecord(bookRecord);
        bookRecords = db.FetchAll();
        setDefaultMode();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void txt_codePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_codePropertyChange
        
    }//GEN-LAST:event_txt_codePropertyChange

    private void txt_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codeKeyTyped
        if (formMode == ModeEnum.ADD) return;
        setUpdateMode();
    }//GEN-LAST:event_txt_codeKeyTyped

    private void txt_titleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_titleKeyTyped
        if (formMode == ModeEnum.ADD) return;
        setUpdateMode();
    }//GEN-LAST:event_txt_titleKeyTyped

    private void txt_priceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyTyped
        if (formMode == ModeEnum.ADD) return;
        setUpdateMode();
    }//GEN-LAST:event_txt_priceKeyTyped

    private void nextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButtonActionPerformed
       if((bookRecords.size() - 1) != currentBookRecord){
           currentBookRecord+=1;
           displayCurrentBookRecord();
       } 
       
    }//GEN-LAST:event_nextButtonActionPerformed

    private void prevButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevButtonActionPerformed
       if(currentBookRecord >0){
          currentBookRecord-=1;
          displayCurrentBookRecord();
       }
    }//GEN-LAST:event_prevButtonActionPerformed

    private void lastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastButtonActionPerformed
        currentBookRecord = bookRecords.size()-1;
        displayCurrentBookRecord();
    }//GEN-LAST:event_lastButtonActionPerformed

    private void firstButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstButtonActionPerformed
        currentBookRecord = 0;
        displayCurrentBookRecord();
    }//GEN-LAST:event_firstButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        db.deleteRecord(bookRecords.get(currentBookRecord));
        bookRecords = db.FetchAll();
        
        if(currentBookRecord > bookRecords.size()-1){
            currentBookRecord = Math.max(bookRecords.size()-1, 0);
        }
        
        setDefaultMode();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void txt_codeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codeKeyPressed
        
    }//GEN-LAST:event_txt_codeKeyPressed

    private void txt_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codeKeyReleased
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
            setDefaultMode();
        }
    }//GEN-LAST:event_txt_codeKeyReleased

    private void txt_titleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_titleKeyReleased
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
            setDefaultMode();
        }
    }//GEN-LAST:event_txt_titleKeyReleased

    private void txt_priceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_priceKeyReleased
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ESCAPE){
            setDefaultMode();
        }
    }//GEN-LAST:event_txt_priceKeyReleased

    private void setEnabledAllButtons(Boolean enabled) {
        addButton.setEnabled(enabled);
        deleteButton.setEnabled(enabled);
        
        //always let the user exit the program, please!
        //exitButton.setEnabled(enabled);
        
        firstButton.setEnabled(enabled);
        lastButton.setEnabled(enabled);
        nextButton.setEnabled(enabled);
        prevButton.setEnabled(enabled);
        updateButton.setEnabled(enabled);
        updateButton.setText("Update");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookMaintenanceUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new BookMaintenanceUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel currentRecordLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton firstButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton lastButton;
    private javax.swing.JButton nextButton;
    private javax.swing.JButton prevButton;
    private javax.swing.JTextField txt_code;
    private javax.swing.JTextField txt_price;
    private javax.swing.JTextField txt_title;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
